services:
  app:
    image: myapp-frontend-dev
    build:
      dockerfile: dev.Dockerfile
      context: ./frontend
    volumes:
      - ./frontend/:/usr/src/app
    container_name: myapp-frontend-dev
    ports:
      - 3000:3000

  server:
    image: myapp-backend-dev
    build:
      dockerfile: dev.Dockerfile
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: myapp-backend-dev
    ports:
      - 3003:3003

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data2:/data/db

volumes:
  mongo_data2:
