services:
  app:
    image: myapp-frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: myapp-frontend

  server:
    image: myapp-backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: myapp-backend
  
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: myapp-reverse-proxy
    depends_on:
      - app
      - server
