services:
  app:
    image: todo-frontend
    volumes:
      - ./todo-frontend/:/usr/src/app
    container_name: todo-frontend

  server:
    image: todo-backend
    volumes:
      - ./todo-backend/:/usr/src/app/
    container_name: todo-backend
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - PORT=3001

  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - ./todo-backend/redis_data:/data

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server

volumes:
  mongo_data:
